/* Generated by Nim Compiler v0.15.2 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -I"C:\Program Files\Nim\lib" -o c:\users\rsharan\documents\github\nippy_test\src\nimcache\nippy_nippy.o c:\users\rsharan\documents\github\nippy_test\src\nimcache\nippy_nippy.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
typedef struct Appobj104011 Appobj104011;
typedef union Event101796 Event101796;
typedef struct Commoneventobj101579 Commoneventobj101579;
typedef struct Windoweventobj101583 Windoweventobj101583;
typedef struct Keyboardeventobj101594 Keyboardeventobj101594;
typedef struct Keysym101060 Keysym101060;
typedef struct Texteditingeventobj101605 Texteditingeventobj101605;
typedef struct Textinputeventobj101616 Textinputeventobj101616;
typedef struct Mousemotioneventobj101624 Mousemotioneventobj101624;
typedef struct Mousebuttoneventobj101635 Mousebuttoneventobj101635;
typedef struct Mousewheeleventobj101647 Mousewheeleventobj101647;
typedef struct Joyaxiseventobj101656 Joyaxiseventobj101656;
typedef struct Joyballeventobj101667 Joyballeventobj101667;
typedef struct Joyhateventobj101678 Joyhateventobj101678;
typedef struct Joybuttoneventobj101687 Joybuttoneventobj101687;
typedef struct Joydeviceeventobj101696 Joydeviceeventobj101696;
typedef struct Controlleraxiseventobj101701 Controlleraxiseventobj101701;
typedef struct Controllerbuttoneventobj101712 Controllerbuttoneventobj101712;
typedef struct Controllerdeviceeventobj101721 Controllerdeviceeventobj101721;
typedef struct Audiodeviceeventobj101726 Audiodeviceeventobj101726;
typedef struct Quiteventobj101773 Quiteventobj101773;
typedef struct Usereventobj101781 Usereventobj101781;
typedef struct Syswmeventobj101791 Syswmeventobj101791;
typedef struct Touchfingereventobj101735 Touchfingereventobj101735;
typedef struct Multigestureeventobj101746 Multigestureeventobj101746;
typedef struct Dollargestureeventobj101757 Dollargestureeventobj101757;
typedef struct Dropeventobj101767 Dropeventobj101767;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell47304 Cell47304;
typedef struct Cellseq47320 Cellseq47320;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29486 Memregion29486;
typedef struct Smallchunk29440 Smallchunk29440;
typedef struct Llchunk29480 Llchunk29480;
typedef struct Bigchunk29442 Bigchunk29442;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29484 Avlnode29484;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47316 Cellset47316;
typedef struct Pagedesc47312 Pagedesc47312;
typedef struct Basechunk29438 Basechunk29438;
typedef struct Freecell29430 Freecell29430;
typedef N_CDECL_PTR(int, TY96423) (NU32 flags0);
typedef NI32 Logcategory102279;
typedef N_CDECL_PTR(void, TY102347) (Logcategory102279 category0, NCSTRING fmt0, ...);
typedef N_CDECL_PTR(NCSTRING, TY97450) (void);
struct  Appobj104011  {
void* window;
void* renderer;
};
typedef N_CDECL_PTR(void*, TY99448) (NCSTRING title0, int x0, int y0, int w0, int h0, NU32 flags0);
typedef N_CDECL_PTR(void*, TY102582) (void* window0, int index0, NU32 flags0);
typedef N_CDECL_PTR(int, TY102765) (void* renderer0, NU8 r0, NU8 g0, NU8 b0, NU8 a0);
typedef N_CDECL_PTR(void, TY102339) (Logcategory102279 category0, NCSTRING fmt0, ...);
typedef N_CDECL_PTR(void, TY102335) (Logcategory102279 category0, NCSTRING fmt0, ...);
typedef N_CDECL_PTR(void, TY102883) (void* renderer0);
typedef N_CDECL_PTR(void, TY99670) (void* window0);
typedef N_CDECL_PTR(void, TY96435) (void);
typedef NI32 Eventkind101513;
struct  Commoneventobj101579  {
Eventkind101513 kind;
NU32 timestamp;
};
typedef NI32 Windoweventid99301;
struct  Windoweventobj101583  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
Windoweventid99301 event;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI32 data1;
NI32 data2;
};
typedef NI32 Scancode99730;
typedef NI32 Keycode100193;
struct  Keysym101060  {
Scancode99730 scancode;
Keycode100193 sym;
NU16 mods;
NU32 unused;
};
struct  Keyboardeventobj101594  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
NU8 state;
NU8 repeat;
NU8 padding2;
NU8 padding3;
Keysym101060 keysym;
};
typedef NIM_CHAR TY101610[32];
struct  Texteditingeventobj101605  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
TY101610 text;
NI32 start;
NI32 length;
};
struct  Textinputeventobj101616  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
TY101610 text;
};
struct  Mousemotioneventobj101624  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
NU32 which;
NU32 state;
NI32 x;
NI32 y;
NI32 xrel;
NI32 yrel;
};
struct  Mousebuttoneventobj101635  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
NU32 which;
NU8 button;
NU8 state;
NU8 clicks;
NU8 padding1;
NI32 x;
NI32 y;
};
typedef NI32 Mousewheeldirection101279;
struct  Mousewheeleventobj101647  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
NU32 which;
NI32 x;
NI32 y;
Mousewheeldirection101279 direction;
};
struct  Joyaxiseventobj101656  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
NU8 axis;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 value;
NU16 padding4;
};
struct  Joyballeventobj101667  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
NU8 ball;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 xrel;
NI16 yrel;
};
struct  Joyhateventobj101678  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
NU8 hat;
NU8 value;
NU8 padding1;
NU8 padding2;
};
struct  Joybuttoneventobj101687  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
NU8 button;
NU8 state;
NU8 padding1;
NU8 padding2;
};
struct  Joydeviceeventobj101696  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
};
typedef NI32 Gamecontrolleraxis101449;
struct  Controlleraxiseventobj101701  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
Gamecontrolleraxis101449 axis;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 value;
NU16 padding4;
};
typedef NI32 Gamecontrollerbutton101474;
struct  Controllerbuttoneventobj101712  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
Gamecontrollerbutton101474 button;
NU8 state;
NU8 padding1;
NU8 padding2;
};
struct  Controllerdeviceeventobj101721  {
Eventkind101513 kind;
NU32 timestamp;
NI32 which;
};
struct  Audiodeviceeventobj101726  {
Eventkind101513 kind;
NU32 timestamp;
NU32 which;
NU8 iscapture;
NU8 padding1;
NU8 padding2;
NU8 padding3;
};
struct  Quiteventobj101773  {
Eventkind101513 kind;
NU32 timestamp;
};
struct  Usereventobj101781  {
Eventkind101513 kind;
NU32 timestamp;
NU32 windowid;
NI32 code;
void* data1;
void* data2;
};
struct  Syswmeventobj101791  {
Eventkind101513 kind;
NU32 timestamp;
void* msg;
};
struct  Touchfingereventobj101735  {
Eventkind101513 kind;
NU32 timestamp;
NI64 touchid;
NI64 fingerid;
float x;
float y;
float dx;
float dy;
float pressure;
};
struct  Multigestureeventobj101746  {
Eventkind101513 kind;
NU32 timestamp;
NI64 touchid;
float dtheta;
float ddist;
float x;
float y;
NU16 numfingers;
NU16 padding;
};
struct  Dollargestureeventobj101757  {
Eventkind101513 kind;
NU32 timestamp;
NI64 touchid;
NI64 gestureid;
NU32 numfingers;
float error;
float x;
float y;
};
struct  Dropeventobj101767  {
Eventkind101513 kind;
NU32 timestamp;
NCSTRING file;
NU32 windowid;
};
typedef NU8 TY101823[56];
union  Event101796  {
Eventkind101513 kind;
Commoneventobj101579 common;
Windoweventobj101583 window;
Keyboardeventobj101594 key;
Texteditingeventobj101605 edit;
Textinputeventobj101616 text;
Mousemotioneventobj101624 motion;
Mousebuttoneventobj101635 button;
Mousewheeleventobj101647 wheel;
Joyaxiseventobj101656 jaxis;
Joyballeventobj101667 jball;
Joyhateventobj101678 jhat;
Joybuttoneventobj101687 jbutton;
Joydeviceeventobj101696 jdevice;
Controlleraxiseventobj101701 caxis;
Controllerbuttoneventobj101712 cbutton;
Controllerdeviceeventobj101721 cdevice;
Audiodeviceeventobj101726 adevice;
Quiteventobj101773 quit;
Usereventobj101781 user;
Syswmeventobj101791 syswm;
Touchfingereventobj101735 tfinger;
Multigestureeventobj101746 mgesture;
Dollargestureeventobj101757 dgesture;
Dropeventobj101767 drop;
TY101823 padding;
};
typedef N_CDECL_PTR(int, TY101857) (Event101796* event0);
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc55802) (void);
struct  Cell47304  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47320  {
NI len;
NI cap;
Cell47304** d;
};
typedef Smallchunk29440* TY29501[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29486  {
NI minlargeobj;
NI maxlargeobj;
TY29501 freesmallchunks;
Llchunk29480* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29442* freechunkslist;
Intset29414 chunkstarts;
Avlnode29484* root;
Avlnode29484* deleted;
Avlnode29484* last;
Avlnode29484* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47316  {
NI counter;
NI max;
Pagedesc47312* head;
Pagedesc47312** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47320 zct;
Cellseq47320 decstack;
Cellseq47320 tempstack;
NI recgclock;
Memregion29486 region;
Gcstat49814 stat;
Cellset47316 marked;
Cellseq47320 additionalroots;
};
typedef N_CDECL_PTR(int, TY102800) (void* renderer0);
typedef N_CDECL_PTR(void, TY102877) (void* renderer0);
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29438  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29440  {
  Basechunk29438 Sup;
Smallchunk29440* next;
Smallchunk29440* prev;
Freecell29430* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29480  {
NI size;
NI acc;
Llchunk29480* next;
};
struct  Bigchunk29442  {
  Basechunk29438 Sup;
Bigchunk29442* next;
Bigchunk29442* prev;
NI align;
NF data;
};
typedef NI TY29419[8];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29419 bits;
};
typedef Avlnode29484* TY29491[2];
struct  Avlnode29484  {
TY29491 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47312  {
Pagedesc47312* next;
NI key;
TY29419 bits;
};
struct  Freecell29430  {
Freecell29430* next;
NI zerofield;
};
N_NIMCALL(NIM_BOOL, init_104017_938895054)(Appobj104011* app0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, exit_104025_938895054)(Appobj104011* app0);
N_NIMCALL(NIM_BOOL, events_104028_938895054)(void);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e0, TNimType* typ0);
N_NIMCALL(void, T938895054_3)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T938895054_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc55802 markerproc0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47304*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47304* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47320* s0, Cell47304* c0);
STRING_LITERAL(T938895054_5, "Press any key...", 16);
extern TY96423 Dl_96422;
extern TY102347 Dl_102346;
extern TY97450 Dl_97449;
extern TY99448 Dl_99447;
extern TY102582 Dl_102581;
extern TY102765 Dl_102764;
extern TY102339 Dl_102338;
extern TY102335 Dl_102334;
extern TFrame* frameptr_18636_1689653243;
extern TY102883 Dl_102882;
extern TY99670 Dl_99669;
extern TY96435 Dl_96434;
extern TY101857 Dl_101856;
extern TNimType NTI100193; /* Keycode */
Appobj104011* app_104069_938895054;
TNimType NTI104011; /* AppObj */
extern TNimType NTI142; /* pointer */
TNimType NTI104009; /* App */
extern Gcheap49818 gch_49858_1689653243;
NIM_BOOL done_104070_938895054;
extern TY102800 Dl_102799;
extern TY102877 Dl_102876;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18636_1689653243;
	frameptr_18636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18636_1689653243 = (*frameptr_18636_1689653243).prev;
}

N_NIMCALL(NIM_BOOL, init_104017_938895054)(Appobj104011* app0) {
	NIM_BOOL result0;
	nimfr("init", "nippy.nim")
{	result0 = (NIM_BOOL)0;
	nimln(22, "nippy.nim");
	{
		int LOC3;
		NCSTRING LOC6;
		nimln(347, "system.nim");
		nimln(22, "nippy.nim");
		LOC3 = (int)0;
		LOC3 = Dl_96422(((NU32) 32));
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(23, "nippy.nim");
		nimln(25, "nippy.nim");
		LOC6 = (NCSTRING)0;
		LOC6 = Dl_97449();
		Dl_102346(((Logcategory102279) 1), "Can\'t initialize SDL: %s", LOC6);
		nimln(26, "nippy.nim");
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA4: ;
	nimln(29, "nippy.nim");
	(*app0).window = Dl_99447("SDL2 App", ((int) 536805376), ((int) 536805376), ((int) 640), ((int) 480), ((NU32) 0));
	nimln(36, "nippy.nim");
	{
		NCSTRING LOC11;
		if (!((*app0).window == NIM_NIL)) goto LA9;
		nimln(37, "nippy.nim");
		nimln(39, "nippy.nim");
		LOC11 = (NCSTRING)0;
		LOC11 = Dl_97449();
		Dl_102346(((Logcategory102279) 1), "Can\'t create window: %s", LOC11);
		nimln(40, "nippy.nim");
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	nimln(43, "nippy.nim");
	(*app0).renderer = Dl_102581((*app0).window, ((int) -1), ((NU32) 6));
	nimln(44, "nippy.nim");
	{
		NCSTRING LOC16;
		if (!((*app0).renderer == NIM_NIL)) goto LA14;
		nimln(45, "nippy.nim");
		nimln(47, "nippy.nim");
		LOC16 = (NCSTRING)0;
		LOC16 = Dl_97449();
		Dl_102346(((Logcategory102279) 1), "Can\'t create renderer: %s", LOC16);
		nimln(48, "nippy.nim");
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA14: ;
	nimln(51, "nippy.nim");
	{
		int LOC19;
		NCSTRING LOC22;
		nimln(347, "system.nim");
		nimln(51, "nippy.nim");
		LOC19 = (int)0;
		LOC19 = Dl_102764((*app0).renderer, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
		if (!!((LOC19 == ((NI32) 0)))) goto LA20;
		nimln(52, "nippy.nim");
		nimln(54, "nippy.nim");
		LOC22 = (NCSTRING)0;
		LOC22 = Dl_97449();
		Dl_102338(((Logcategory102279) 5), "Can\'t set draw color: %s", LOC22);
		nimln(55, "nippy.nim");
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA20: ;
	nimln(57, "nippy.nim");
	Dl_102334(((Logcategory102279) 0), "SDL initialized successfully");
	nimln(58, "nippy.nim");
	result0 = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, exit_104025_938895054)(Appobj104011* app0) {
	nimfr("exit", "nippy.nim")
	nimln(63, "nippy.nim");
	Dl_102882((*app0).renderer);
	nimln(64, "nippy.nim");
	Dl_99669((*app0).window);
	nimln(65, "nippy.nim");
	Dl_102334(((Logcategory102279) 0), "SDL shutdown completed");
	nimln(66, "nippy.nim");
	Dl_96434();
	popFrame();
}

N_NIMCALL(NIM_BOOL, events_104028_938895054)(void) {
	NIM_BOOL result0;
	Event101796 e0;
	nimfr("events", "nippy.nim")
{	result0 = (NIM_BOOL)0;
	nimln(72, "nippy.nim");
	result0 = NIM_FALSE;
	memset((void*)(&e0), 0, sizeof(e0));
	{
		nimln(75, "nippy.nim");
		while (1) {
			int LOC3;
			nimln(347, "system.nim");
			nimln(75, "nippy.nim");
			LOC3 = (int)0;
			LOC3 = Dl_101856((&e0));
			if (!!((LOC3 == ((NI32) 0)))) goto LA2;
			nimln(78, "nippy.nim");
			{
				if (!(e0.kind == ((Eventkind101513) 256))) goto LA6;
				nimln(79, "nippy.nim");
				result0 = NIM_TRUE;
				goto BeforeRet;
			}
			goto LA4;
			LA6: ;
			{
				nimln(82, "nippy.nim");
				if (!(e0.kind == ((Eventkind101513) 768))) goto LA9;
				nimln(84, "nippy.nim");
				Dl_102334(((Logcategory102279) 0), "Pressed %s", reprEnum((NI)e0.key.keysym.sym, (&NTI100193))->data);
				nimln(87, "nippy.nim");
				{
					if (!(e0.key.keysym.sym == ((Keycode100193) 27))) goto LA13;
					nimln(88, "nippy.nim");
					result0 = NIM_TRUE;
					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA4;
			LA9: ;
			LA4: ;
		} LA2: ;
	}
	}BeforeRet: ;
	popFrame();
	return result0;
}
N_NIMCALL(void, T938895054_3)(void* p, NI op) {
	Appobj104011* a;
	a = (Appobj104011*)p;
}
N_NIMCALL(void, T938895054_4)(void) {
	nimGCvisit((void*)app_104069_938895054, 0);
}

static N_INLINE(Cell47304*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47304* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47304*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell47304*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47304))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47304* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(214, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(274, "gc.nim");
	{
		Cell47304* c0;
		nimln(347, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(275, "gc.nim");
		c0 = usrtocell_51440_1689653243(src0);
		nimln(182, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(277, "gc.nim");
	{
		Cell47304* c0;
		nimln(347, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(278, "gc.nim");
		c0 = usrtocell_51440_1689653243((*dest0));
		nimln(279, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(280, "gc.nim");
			rtladdzct_52601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(281, "gc.nim");
	(*dest0) = src0;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, nippy_nippyInit000)(void) {
	Appobj104011* LOC1;
	nimfr("nippy", "nippy.nim")
nimRegisterGlobalMarker(T938895054_4);
	nimln(96, "nippy.nim");
	LOC1 = (Appobj104011*)0;
	LOC1 = (Appobj104011*) newObj((&NTI104009), sizeof(Appobj104011));
	(*LOC1).window = NIM_NIL;
	(*LOC1).renderer = NIM_NIL;
	asgnRefNoCycle((void**) (&app_104069_938895054), LOC1);
	nimln(97, "nippy.nim");
	done_104070_938895054 = NIM_FALSE;
	nimln(99, "nippy.nim");
	{
		NIM_BOOL LOC4;
		LOC4 = (NIM_BOOL)0;
		LOC4 = init_104017_938895054(app_104069_938895054);
		if (!LOC4) goto LA5;
		nimln(101, "nippy.nim");
		printf("%s\015\012", ((NimStringDesc*) &T938895054_5)? (((NimStringDesc*) &T938895054_5))->data:"nil");
		fflush(stdout);
		{
			nimln(104, "nippy.nim");
			while (1) {
				if (!!(done_104070_938895054)) goto LA8;
				nimln(106, "nippy.nim");
				{
					int LOC11;
					NCSTRING LOC14;
					nimln(347, "system.nim");
					nimln(106, "nippy.nim");
					LOC11 = (int)0;
					LOC11 = Dl_102799((*app_104069_938895054).renderer);
					if (!!((LOC11 == ((NI32) 0)))) goto LA12;
					nimln(107, "nippy.nim");
					nimln(109, "nippy.nim");
					LOC14 = (NCSTRING)0;
					LOC14 = Dl_97449();
					Dl_102338(((Logcategory102279) 5), "Can\'t clear screen: %s", LOC14);
				}
				LA12: ;
				nimln(112, "nippy.nim");
				Dl_102876((*app_104069_938895054).renderer);
				nimln(115, "nippy.nim");
				done_104070_938895054 = events_104028_938895054();
			} LA8: ;
		}
	}
	LA5: ;
	nimln(119, "nippy.nim");
	exit_104025_938895054(app_104069_938895054);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nippy_nippyDatInit000)(void) {
static TNimNode* T938895054_2[2];
static TNimNode T938895054_0[3];
NTI104011.size = sizeof(Appobj104011);
NTI104011.kind = 18;
NTI104011.base = 0;
NTI104011.flags = 3;
T938895054_2[0] = &T938895054_0[1];
T938895054_0[1].kind = 1;
T938895054_0[1].offset = offsetof(Appobj104011, window);
T938895054_0[1].typ = (&NTI142);
T938895054_0[1].name = "window";
T938895054_2[1] = &T938895054_0[2];
T938895054_0[2].kind = 1;
T938895054_0[2].offset = offsetof(Appobj104011, renderer);
T938895054_0[2].typ = (&NTI142);
T938895054_0[2].name = "renderer";
T938895054_0[0].len = 2; T938895054_0[0].kind = 2; T938895054_0[0].sons = &T938895054_2[0];
NTI104011.node = &T938895054_0[0];
NTI104009.size = sizeof(Appobj104011*);
NTI104009.kind = 22;
NTI104009.base = (&NTI104011);
NTI104009.flags = 2;
NTI104009.marker = T938895054_3;
}

