/* Generated by Nim Compiler v0.15.2 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -I"C:\Program Files\Nim\lib" -o c:\users\rsharan\devspace\nim\nippy\src\nimcache\nippy_sdl.o c:\users\rsharan\devspace\nim\nippy\src\nimcache\nippy_sdl.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY96423) (NU32 flags0);
typedef N_CDECL_PTR(NCSTRING, TY97450) (void);
typedef N_CDECL_PTR(void*, TY99448) (NCSTRING title0, int x0, int y0, int w0, int h0, NU32 flags0);
typedef N_CDECL_PTR(void*, TY102582) (void* window0, int index0, NU32 flags0);
typedef N_CDECL_PTR(int, TY102765) (void* renderer0, NU8 r0, NU8 g0, NU8 b0, NU8 a0);
typedef N_CDECL_PTR(void, TY102883) (void* renderer0);
typedef N_CDECL_PTR(void, TY99670) (void* window0);
typedef N_CDECL_PTR(void, TY96435) (void);
typedef N_CDECL_PTR(int, TY102800) (void* renderer0);
typedef N_CDECL_PTR(void, TY102877) (void* renderer0);
typedef N_CDECL_PTR(void, TY103271) (NU32 ms0);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(T2910579083_4, "SDL2.dll", 8);
STRING_LITERAL(T2910579083_5, "SDL2.dll", 8);
static void* T2910579083_2;
TY96423 Dl_96422;
TY97450 Dl_97449;
TY99448 Dl_99447;
TY102582 Dl_102581;
TY102765 Dl_102764;
TY102883 Dl_102882;
TY99670 Dl_99669;
TY96435 Dl_96434;
TY102800 Dl_102799;
TY102877 Dl_102876;
TY103271 Dl_103270;
extern TFrame* frameptr_18636_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18636_1689653243;
	frameptr_18636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18636_1689653243 = (*frameptr_18636_1689653243).prev;
}
NIM_EXTERNC N_NOINLINE(void, nippy_sdlInit000)(void) {
	nimfr("sdl", "sdl.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nippy_sdlDatInit000)(void) {
if (!((T2910579083_2 = nimLoadLibrary((NimStringDesc*) &T2910579083_4))
)) nimLoadLibraryError((NimStringDesc*) &T2910579083_5);
	Dl_96422 = (TY96423) nimGetProcAddr(T2910579083_2, "SDL_Init");
	Dl_97449 = (TY97450) nimGetProcAddr(T2910579083_2, "SDL_GetError");
	Dl_99447 = (TY99448) nimGetProcAddr(T2910579083_2, "SDL_CreateWindow");
	Dl_102581 = (TY102582) nimGetProcAddr(T2910579083_2, "SDL_CreateRenderer");
	Dl_102764 = (TY102765) nimGetProcAddr(T2910579083_2, "SDL_SetRenderDrawColor");
	Dl_102882 = (TY102883) nimGetProcAddr(T2910579083_2, "SDL_DestroyRenderer");
	Dl_99669 = (TY99670) nimGetProcAddr(T2910579083_2, "SDL_DestroyWindow");
	Dl_96434 = (TY96435) nimGetProcAddr(T2910579083_2, "SDL_Quit");
	Dl_102799 = (TY102800) nimGetProcAddr(T2910579083_2, "SDL_RenderClear");
	Dl_102876 = (TY102877) nimGetProcAddr(T2910579083_2, "SDL_RenderPresent");
	Dl_103270 = (TY103271) nimGetProcAddr(T2910579083_2, "SDL_Delay");
}

